### ISSUE TITLE
Lodash Peer Dependency

### ISSUE THREAD

**Issue by santhosh883** [CurtisHumphrey/react-keyboard-shortcuts#2]
Lodash Peer dependency restricts the library from using in apps where underscore is already being used. It would be nice to remove lodash peer dependency and use it as dependency.

**Comment by CurtisHumphrey** [comment]
You are right it would be a good idea. PR welcome, otherwise, I get to it next time I update this project.

**Comment by CurtisHumphrey** [comment]
#4 - Great job @santhosh883 and thanks.
